#! /usr/bin/env python

import logging
import os
import platform

from lab.calls.call import Call
from lab import tools

tools.configure_logging()

logging.info(f"node: {platform.node()}")

run_log = open("run.log", "w")
run_err = open("run.err", "w", buffering=1)  # line buffering
redirects = {"stdout": run_log, "stderr": run_err}

# Make sure we're in the run directory.
os.chdir(os.path.dirname(os.path.abspath(__file__)))

Call(['../../run-apptainer.sh', '../../h_policy.plan.sif', 'dk', 'domain.pddl', 'problem.pddl', 'sas_plan', '1800', '8192'], hard_stderr_limit=10240, hard_stdout_limit=51200, memory_limit=None, name='run-apptainer', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/proj/dfsplan/users/x_jense/ipc2023-learning/scripts/experiments/.venv/bin/python3', '../../planning-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='planning_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/proj/dfsplan/users/x_jense/ipc2023-learning/scripts/experiments/.venv/bin/python3', '../../runsolver-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='runsolver_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()


for f in [run_log, run_err]:
    f.close()
    if os.path.getsize(f.name) == 0:
        os.remove(f.name)
