#! /usr/bin/env python

import logging
import os
import platform

from lab.calls.call import Call
from lab import tools

tools.configure_logging()

logging.info(f"node: {platform.node()}")

run_log = open("run.log", "w")
run_err = open("run.err", "w", buffering=1)  # line buffering
redirects = {"stdout": run_log, "stderr": run_err}

# Make sure we're in the run directory.
os.chdir(os.path.dirname(os.path.abspath(__file__)))

Call(['/usr/bin/python3', '../../code/fast-downward.py', '--alias', 'lama-first', '--transform-task', '//fd-partial-grounding/builds/release/bin/preprocess-h2', '--transform-task-options', 'h2_time_limit,300', '--incremental-grounding', '--incremental-grounding-search-time-limit', '300', '--incremental-grounding-increment-percentage', '20', '--overall-time-limit', '1800', '--overall-memory-limit', '4096', 'domain.pddl', 'problem.pddl', '--translate-options', '--grounding-action-queue-ordering', 'ipc23-single-queue', '--batch-evaluation', '--trained-model-folder', '/proj/dfsplan/users/x_jense/ipc2023-learning/scripts/experiments/data/2023-06-04-test-learning/runs-00001-00100/00011/data/smac-1/smac-search/incumbent', '--ignore-bad-actions', '--termination-condition', 'goal-relaxed-reachable', 'percentage', '10'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='planner', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/usr/bin/python3', '../../exitcode-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='exitcode_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/usr/bin/python3', '../../single-search-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='single_search_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/usr/bin/python3', '../../translator-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='translator_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/usr/bin/python3', '../../planner-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='planner_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()

Call(['/usr/bin/python3', '../../goodops-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='goodops_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()


for f in [run_log, run_err]:
    f.close()
    if os.path.getsize(f.name) == 0:
        os.remove(f.name)
